### ISSUE TITLE
Data upload

### ISSUE THREAD

**Issue by perezkelly** [clld/amsd#17]
Could we do another data upload, and see if it all goes smoothly? 

Here is the revised link for everything: 
https://www.dropbox.com/sh/j3qw2ki411s1um3/AAA_vPN1P0JbvVzsS0dnJuKZa?dl=0

Inside this link the relevant up-to-date text file is: records.tsv
And the up-to-date image folder is: Message_sticks_images_all

**Comment by Bibiko** [comment]
It didn't go really smoothly. Which app are you using for editing this table? I'll modify the conversion python script in amsd-data, then you can install this repo and run the script against your new records.tsv file in order to get all these warnings and errors resp.
 
1) except for the first line (the header) all other lines have 43 columns instead of 42
2) incorrect structure of column `ling_area` for these rows:
line 31 : Chirila: Minkin  G26: Mingginda  Glottolog: mink1237
line 260 : Chirila: Jiwarliny  Austlang: A88: Juwaliny  Glottocode: djuw1238
3) incorrect lat/long notation for (standard is e.g. 22°17'29.48"S  135°57'49.35"E):
line 1076 : 16.0703° S 136.3072° E
4) line 417: has too many filled columns 
5) and these images are new and should be uploaded:
no image match for 'Olena Tykhostup  Piers Kelly'
no image match for 'y-1904-Klaatsch-MalakMalak-Erkenbrecht2010p37.png'
no image match for '1958-Artefact-fig.5A-Mountford-The_Tiwi-p.99.png'
no image match for '1958-Artefact-fig.5B-Mountford-The_Tiwi-p.99.png'
no image match for '1958-Artefact-fig.5C-Mountford-The_Tiwi-p.99.png'
no image match for '1958-Artefact-fig.5D-Mountford-The_Tiwi-p.99.png'
no image match for '1958-Artefact-fig.6J-Mountford-The_Tiwi-p.101.png'
no image match for '1958-Artefact-fig.6A-Mountford-The_Tiwi-p.101.png'
no image match for '1958-Artefact-fig.6E-Mountford-The_Tiwi-p.101.png'
no image match for '1958-Artefact-fig.5E-Mountford-The_Tiwi-p.99.png'
no image match for '1958-Artefact-fig.5F-Mountford-The_Tiwi-p.99.png'
no image match for '1958-Artefact-fig.5G-Mountford-The_Tiwi-p.99.png'
no image match for '1958-Artefact-fig.5H-Mountford-The_Tiwi-p.99.png'
no image match for '1958-Artefact-fig.6B-Mountford-The_Tiwi-p.101.png'
no image match for '1958-Artefact-fig.6C-Mountford-The_Tiwi-p.101.png'
no image match for '1958-Artefact-fig.6F-Mountford-The_Tiwi-p.101.png'
no image match for '1958-Artefact-fig.6G-Mountford-The_Tiwi-p.101.png'
no image match for '1958-Artefact-fig.6H-Mountford-The_Tiwi-p.101.png'
no image match for '1958-Artefact-fig.7A-Mountford-The_Tiwi-p.105.png'
no image match for '1958-Artefact-fig.7B-Mountford-The_Tiwi-p.105.png'
no image match for '1958-Artefact-fig.7C-Mountford-The_Tiwi-p.105.png'
no image match for '1958-Artefact-fig.7D-Mountford-The_Tiwi-p.105.png'
no image match for '1958-Artefact-fig.6D-Mountford-The_Tiwi-p.101.png'
no image match for 'BLM19350712.jpg'
no image match for 'LA2015P120.png'
no image match for 'BLM19350711_01.jpg'
no image match for 'BLM19350711_02.jpg'
no image match for '20190425-ebay-s-l1600_00.jpg'
no image match for '20190425-ebay-s-l1600_01.jpg'
no image match for '20190425-ebay-s-l1600_02.jpg'
no image match for '20190425-ebay-s-l1600_03.jpg'
no image match for '20190425-ebay-s-l1600_04.jpg'
no image match for '20190425-ebay-s-l1600_05.jpg'
no image match for '20190425-ebay-s-l1600_06.jpg'
no image match for '20190502-KatrinaWright1.jpg'
no image match for '20190502-KatrinaWright2.jpg'
no image match for '20190502-KatrinaWright3.jpg'
no image match for '20190502-KatrinaWright4.jpg'
no image match for '20190606-ebay-s-l1600_01.jpg'
no image match for '20190606-ebay-s-l1600_02.jpg'
no image match for '20190606-ebay-s-l1600_03.jpg'
no image match for '20190606-ebay-s-l1600_04.jpg'
no image match for '20190606-ebay-s-l1600_05.jpg'
no image match for '20190606-ebay-s-l1600_06.jpg'
no image match for '20190606-ebay-s-l1600_07.jpg'
no image match for '20190606-ebay-s-l1600_08.jpg'
no image match for '20190607-ebay-s-l1600_00.jpg'
no image match for '20190607-ebay-s-l1600_01.jpg'
no image match for '20190607-ebay-s-l1600_02.jpg'
no image match for '20190607-ebay-s-l1600_03.jpg'

**Comment by Bibiko** [comment]
**And more importantly:** Did you use the **latest** version of records.tsv in https://github.com/clld/amsd-data/blob/master/org_data/records.tsv ? Since 23 days ago I've already fixed several duplicates/typos/errors/etc. - see
https://github.com/clld/amsd-data/commit/27862a57920aaa6e0c84cfb3ae1912a3d3ddc71e#diff-6dd12d02084c2164ec90858392750f4d

**Comment by perezkelly** [comment]
Hi, thanks for the error list!
I can fix all that up and add the missing images to the folder. It looks
like they got misfiled when we moved everything out of Nextcloud.

But before I do this: I didn't realise that you were making direct
modifications to the records.tsv file uploaded last year. In earlier phases
of the project I just sent you updated versions of records.tsv to be
uploaded each time there was a new batch of data. I would prefer to keep
doing it this way if that's OK.

The way it has been working so far is that the research assistants have
been adding all new data to the OCCAMs data entry interface, which is a lot easier than trying
to edit a .tsv file directly. Then from OCCAMS we export an updated .tsv
file to be uploaded to the AMSD. In other words, records.tsv is replaced
from time to time as the database expands.

So if there are typos and other issues, it's much better if we can do it
upstream in OCCAMS. I'm sorry if you were doing it on the old records.tsv
file – I didn't notice that was happening and I hope it didn't waste too
much of your time!

If you want to meet up to discuss the ideal workflow for data uploads I'm
available today and tomorrow, or next week.

Piers

**Comment by Bibiko** [comment]
I've just uploaded the improved script `to_csv.py` - I added a similarity check to come up with, esp. source citations, which differ only in a '.' or an additional space character or different usage of quotes or etc. -  now you can clone the repo https://github.com/clld/amsd-data - replace `org_data/records.tsv` with your new version, and run in folder `src/pyamsd` `python ./to_csv.py` to get this messages (I removed the warnings about wrong number of columns and you can see which sources I had already cleaned in the repo file):

amsd-data/src/pyamsd$ python3 ./to_csv.py 
Error: ling_area_1 in line 31 has wrong structure: Chirila: Minkin  G26: Mingginda  Glottolog: mink1237
Error: ling_area_1 in line 260 has wrong structure: Chirila: Jiwarliny  Austlang: A88: Juwaliny  Glottocode: djuw1238
Error: count of columns in line 417 is 44 NOT 42
Error: check lat/long notation in line 417 for "The South Australian Museum"
Error: too many filled columns for line 417
Error: ling_area_1 in line 1056 has wrong structure: AUSTLANG: N22: Malak Malak  Chirila: Malak Malak  Glottolog: mull1237
Error: check lat/long notation in line 1076 for "16.0703° S"
Error: check lat/long notation in line 1076 for "136.3072° E"
sim check: source_citation
Howitt, A. W. 1889. “Notes on Australian Message Sticks and Messengers”. The Journal of the Anthropological Institute of Great Britain and Ireland 18. [Royal Anthropological Institute of Great Britain and Ireland, Wiley]: 314–32
Howitt, A. W. 1889. "Notes on Australian Message Sticks and Messengers". The Journal of the Anthropological Institute of Great Britain and Ireland 18. [Royal Anthropological Institute of Great Britain and Ireland, Wiley]: 314–32

sim check: source_citation
Zeitschrift für Ethnologie 72 (4/6): 328-352.
Zeitschrift für Ethnologie 72 (4/6):328-352.

sim check: source_citation
Mathews, Robert Hamilton. 1897. “Message-sticks used by the Aborigines of Australia “
Mathews, Robert Hamilton. 1897. "Message-sticks used by the Aborigines of Australia"

sim check: source_citation
Hamlyn Harris, R. 1918. “On messages and ‘message sticks’ employed among the Queensland Aborigines.”
Hamlyn-Harris, R. 1918. “On messages and ‘message sticks’ employed among the Queensland Aborigines.”

sim check: source_citation
Transactions of the Royal Society of South Australia 62 (1):122-126
Transactions of the Royal Society of South Australia 62 (1):122-126.

sim check: source_citation
Curr, Edward M. 1886. The Australian race: It's origin, languages, customs, place of landing in Australia and the routes by which it spread itself over that continent. 5 vols. Vol. 1. Melbourne: John Ferres.
Curr, Edward M. 1887. The Australian race: Its origin, languages, customs, place of landing in Australia and the routes by which it spread itself over that continent. 5 vols. Vol. 3. Melbourne: John Ferres.

sim check: source_citation
Museum collection
Museum Collection

sim check: ling_area
Wanyiwalku|D21|Wanyiwalku|bagu1250
Wanyiwalku|D21|Wanyiwalku|no code

sim check: ling_area
Waanyi|G23|Waanyi|no code
Karanya|L32|Karanya|no code

sim check: ling_area
Guwinmal|E49|Guwinmal|no code
Mambura|E49|Guwinmal|no code

no image match for 'Olena Tykhostup  Piers Kelly'
no image match for 'y-1904-Klaatsch-MalakMalak-Erkenbrecht2010p37.png'
no image match for '1958-Artefact-fig.5A-Mountford-The_Tiwi-p.99.png'
no image match for '1958-Artefact-fig.5B-Mountford-The_Tiwi-p.99.png'
no image match for '1958-Artefact-fig.5C-Mountford-The_Tiwi-p.99.png'
no image match for '1958-Artefact-fig.5D-Mountford-The_Tiwi-p.99.png'
no image match for '1958-Artefact-fig.6J-Mountford-The_Tiwi-p.101.png'
no image match for '1958-Artefact-fig.6A-Mountford-The_Tiwi-p.101.png'
no image match for '1958-Artefact-fig.6E-Mountford-The_Tiwi-p.101.png'
no image match for '1958-Artefact-fig.5E-Mountford-The_Tiwi-p.99.png'
no image match for '1958-Artefact-fig.5F-Mountford-The_Tiwi-p.99.png'
no image match for '1958-Artefact-fig.5G-Mountford-The_Tiwi-p.99.png'
no image match for '1958-Artefact-fig.5H-Mountford-The_Tiwi-p.99.png'
no image match for '1958-Artefact-fig.6B-Mountford-The_Tiwi-p.101.png'
no image match for '1958-Artefact-fig.6C-Mountford-The_Tiwi-p.101.png'
no image match for '1958-Artefact-fig.6F-Mountford-The_Tiwi-p.101.png'
no image match for '1958-Artefact-fig.6G-Mountford-The_Tiwi-p.101.png'
no image match for '1958-Artefact-fig.6H-Mountford-The_Tiwi-p.101.png'
no image match for '1958-Artefact-fig.7A-Mountford-The_Tiwi-p.105.png'
no image match for '1958-Artefact-fig.7B-Mountford-The_Tiwi-p.105.png'
no image match for '1958-Artefact-fig.7C-Mountford-The_Tiwi-p.105.png'
no image match for '1958-Artefact-fig.7D-Mountford-The_Tiwi-p.105.png'
no image match for '1958-Artefact-fig.6D-Mountford-The_Tiwi-p.101.png'
no image match for 'BLM19350712.jpg'
no image match for 'LA2015P120.png'
no image match for 'BLM19350711_01.jpg'
no image match for 'BLM19350711_02.jpg'
no image match for '20190425-ebay-s-l1600_00.jpg'
no image match for '20190425-ebay-s-l1600_01.jpg'
no image match for '20190425-ebay-s-l1600_02.jpg'
no image match for '20190425-ebay-s-l1600_03.jpg'
no image match for '20190425-ebay-s-l1600_04.jpg'
no image match for '20190425-ebay-s-l1600_05.jpg'
no image match for '20190425-ebay-s-l1600_06.jpg'
no image match for '20190502-KatrinaWright1.jpg'
no image match for '20190502-KatrinaWright2.jpg'
no image match for '20190502-KatrinaWright3.jpg'
no image match for '20190502-KatrinaWright4.jpg'
no image match for '20190606-ebay-s-l1600_01.jpg'
no image match for '20190606-ebay-s-l1600_02.jpg'
no image match for '20190606-ebay-s-l1600_03.jpg'
no image match for '20190606-ebay-s-l1600_04.jpg'
no image match for '20190606-ebay-s-l1600_05.jpg'
no image match for '20190606-ebay-s-l1600_06.jpg'
no image match for '20190606-ebay-s-l1600_07.jpg'
no image match for '20190606-ebay-s-l1600_08.jpg'
no image match for '20190607-ebay-s-l1600_00.jpg'
no image match for '20190607-ebay-s-l1600_01.jpg'
no image match for '20190607-ebay-s-l1600_02.jpg'
no image match for '20190607-ebay-s-l1600_03.jpg'

**Comment by perezkelly** [comment]
Hi Hans,
I'm just working my way through this error list now. It won't take long.

A few oddities:

- There are one or two images that were already in the image folder despite being on this error list (eg, BLM19350711_01.jpg).

- There are also a few errors that don't look like errors to me. Eg, _Error: ling_area_1 in line 260 has wrong structure: Chirila: Jiwarliny Austlang: A88: Juwaliny Glottocode: djuw1238_  This looks well formed to me.

Otherwise, everything else can be dealt with.

A question: 
I have absolutely zero python knowledge and very limited github experience. Is there a time that I could come into the institute to meet you so you can show me how to run your improved script to check for errors/similarities etc? 
I would like to write down the step-by-step process for how to check each new records.tsv file then upload it, and how to upload a new image folder. If I'm able to do this by myself it should save everyone else time!

**Comment by Bibiko** [comment]
> There are one or two images that were already in the image folder despite being on this error list (eg, BLM19350711_01.jpg).

This means that these images are not yet uploaded to the caster server


> There are also a few errors that don't look like errors to me. Eg, Error: ling_area_1 in line 260 has wrong structure: Chirila: Jiwarliny Austlang: A88: Juwaliny Glottocode: djuw1238 This looks well formed to me.

it looks like but it isn't. Your default notation is that in front of `Austlang` and `Glottolog` has to occur **two** spaces, and not only one ;) 

Re Python & Co we could meet next week.

**Comment by perezkelly** [comment]
Great, I can do any afternoon next week. 
What days will you be in Jena?
